import React from "react";

export const wording = {
  "zh-tw": {
    "title-line-1": "區塊鏈溯源",
    "title-line-2": "賀禮服務平台",
    "order-info": "訂單資訊",
    "illustration-title": "禮重 ‧ 情意濃",
    "make-gcard": "製作賀卡",
    "brand-intro": "品牌介紹",
    "receiver-feedback": "收禮者回饋",
    sender: "送禮者",
    receiver: "收禮者",
    "oi-explain-part-1": "以下是您訂購送給",
    "oi-explain-part-2": "的禮品內容",
    "gift-intro": "禮品介紹",
    "farm-info": "農場資訊",
    certificate: "檢驗證書",
    "il-explain-part-1": "錄製給",
    "il-explain-part-2": "的一段影音，",
    "il-explain-part-3": "讓他/她可以透過掃描禮盒上的QR Code，",
    "il-explain-part-4": "看見、聽見你的祝福",
    "make-gcard-part-1": "製作給",
    "make-gcard-part-2": "的賀卡",
    "gcard-instant-preview": "賀卡即時預覽",
    "sender-name": "送禮者署名",
    "sender-name-example": "如：商田公司 林啟森董事長",
    "upload-greet-vid": "祝賀影片拍攝及上傳",
    "upload-vid-complete": "影片上傳完成！請於上方即時預覽",
    "greet-content": "祝賀內容",
    "greet-content-example": "(範例) 祝您身體健康、萬事如意",
    "save-and-send": "儲存並寄出",
    "received-notification-part-1": "太好了！",
    "received-notification-part-2": "已收到您的禮物",
    "received-notification-part-3": "並觀看了您的祝福賀卡",
    "received-notification-part-4": "次",
    "gcard-sent-part-1": "您製作給",
    "gcard-sent-part-2": "的賀卡已成功寄出！",
    "ask-for-preview": "是否預覽完稿頁面？",
    "agree-preview": "是，開啟預覽頁",
    "refuse-preview": "否，留在本頁",
    "gcard-save-fail": "賀卡儲存失敗，請聯繫客服人員，謝謝！",
    "use-example": "套用範本",
    "order-not-found": "系統查無您的訂單，請聯繫客服。",
    "record-greet-vid-hint": "請錄製您的祝賀影片",
    "record-thank-vid-hint": "請錄製您的感謝影片",
    "upload-below": "，由下方表單上傳",
    "gcard-from-part-1": "來自",
    "gcard-from-part-2": "的祝福",
    "tcard-from-part-1": "來自",
    "tcard-from-part-2": "的感謝",
    "nthu-hsnl": "清華大學高速網路研究室",
    "research-field": "研究領域",
    "ai-edu": "人工智慧教育大數據",
    "smart-agri": "智慧科技農業",
    "lora-wan": "長距離低功耗物聯網無線網路",
    aiot: "人工智慧物聯網 (AIoT)",
    "agri-blockchain": "農業區塊鏈服務平台",
    "cyber-security": "網路安全",
    "chia-wei": "商田實業有限公司",
    "chia-wei-intro":
      "商田實業有限公司是一家國際貿易公司，專門進口日本及其他國家的優質農產品。主要通路為台灣高級百貨公司及超級市場。",
    "watch-gcard": "觀看賀卡",
    "gift-intro-and-blockchain": "禮品介紹 & 區塊鏈溯源",
    "make-tcard": "製作回禮感謝卡",
    "gift-slogan-part-1": "信賴 ‧ 溫度",
    "gift-slogan-part-2": "一份精心為您準備的禮物",
    "sms-hint-part-1": "若送禮者有錄製，寄送給您的影音祝福，",
    "sms-hint-part-2": "您應已收到一封含有禮物密碼的手機簡訊",
    "watch-gcard-from-sender": "觀看送禮者給您的影音祝福",
    "enter-gift-code-part-1": "",
    "enter-gift-code-part-2": "請輸入簡訊禮物密碼",
    "gift-code": "簡訊禮物密碼",
    "send-gift-code": "送出",
    "send-tcard-succeed-part-1": "您給",
    "send-tcard-succeed-part-2": "的回禮感謝卡已成功寄出！",
    "tcard-save-fail": "回禮感謝卡儲存失敗，請聯繫客服人員，謝謝！",
    "make-tcard-part-1": "製作給",
    "make-tcard-part-2": "的回禮感謝卡",
    "tcard-instant-preview": "感謝卡即時預覽",
    "feedback-name": "回禮者署名",
    "upload-thank-vid": "回禮感謝影片拍攝及上傳",
    "thank-content": "回禮內容",
    "enter-code-error": "您輸入的禮物密碼有誤，請檢查後更正。",
    opening: "開幕",
    promoting: "升遷",
    "new-house": "新居",
    birthday: "生日",
    "new-year": "新年",
    "shooting-now":"立即拍攝",
    "choose-file":"選擇檔案",
    "vertical-vid-hint":"(為畫面效果，儘量選用「直式」影片)"
  },
  jp: {
    "title-line-1": "ブロックチェーン",
    "title-line-2": "のトレーサビリティ",
    "title-line-3": "ギフトサービス",
    "title-line-4": "フォーム",
    "order-info": "ご注文詳細",
    "illustration-title": "心込めギフト",
    "make-gcard": "お祝いカードを作ります",
    "brand-intro": "ブラント紹介",
    "receiver-feedback": "受礼者(様)のご返事",
    sender: "ギフト贈り主",
    receiver: "ギフト受礼者(様)",
    "oi-explain-part-1": "ご注文頂いた",
    "oi-explain-part-2": "へのギフトされる内容は下記でございます",
    "gift-intro": "ギフト内容",
    "farm-info": "農場情報",
    certificate: "検査証明書",
    "il-explain-part-1": "のためにビデオを録音しましょう。",
    "il-explain-part-2": "は箱にあるQRコードをスキャンされたら、",
    "il-explain-part-3": "ビデオでお祝いを見られるし、聞こえます。",
    "make-gcard-part-1": "",
    "make-gcard-part-2": "にお祝いカードを作りましょう",
    "gcard-instant-preview": "お祝いカードをインスタントプレビュー",
    "sender-name": "ギフト贈り主サイン",
    "sender-name-example": "例えば：商田会社林啟森会長",
    "upload-greet-vid": "お祝いビデオの撮影とアップロード",
    "upload-vid-complete":
      "ビデオのアップロード成功！上でプレビューしてください",
    "greet-content": "お祝い内容",
    "greet-content-example":
      "(例)ご幸福ご健康を祈ります。萬事順調をお祈りします。",
    "save-and-send": "保存して送信",
    "received-notification-part-1": "良かった！",
    "received-notification-part-2": "はギフトを受け取りました",
    "received-notification-part-3": "作られたお祝いカードを",
    "received-notification-part-4": "回をご覧になりました",
    "gcard-sent-part-1": "",
    "gcard-sent-part-2": "のために、作られたお祝いカードは送信成功！",
    "ask-for-preview": "完成したページをプレビューしますか？",
    "agree-preview": "はい、プレビューページを開きます",
    "refuse-preview": "いいえ、そのままこのページにします",
    "gcard-save-fail":
      "お祝いカードが保存できません、カスタマーサービスにお問い合わせください",
    "use-example": "範例を使用します",
    "order-not-found":
      "システムがご注文を見つけられません。カスタマーサービスにご連絡ください。",
    "record-greet-vid-hint": "お祝いビデオを録画して、",
    "record-thank-vid-hint": "感謝するビデオを録画して、",
    "upload-below": "下のフォームからアップロードしてください",
    "gcard-from-part-1": "",
    "gcard-from-part-2": "からのお祝い",
    "tcard-from-part-1": "",
    "tcard-from-part-2": "からの感謝",
    "nthu-hsnl": "清華大學高速ネット研究室",
    "research-field": "研究エリア",
    "ai-edu": "人工知能教育ビッグデータ",
    "smart-agri": "スマートテクノロジー農業",
    "lora-wan": "長距離低電力IoTワイヤレスネットワーク",
    aiot: "人工知能モノのインターネット（AIoT）",
    "agri-blockchain": "農業ブロックチェーンサービスプラットフォーム",
    "cyber-security": "サイバーセキュリティ",
    "chia-wei": "商田実業有限会社",
    "chia-wei-intro":
      "商田実業有限会社は日本およびその他の国からの高品質の農産物の輸入を専門とする会社です。台湾の高級デパートとスーパーに商品を提供させていただきます。",
    "watch-gcard": "お祝いカードをご覧ください",
    "gift-intro-and-blockchain":
      "ギフト紹介＆ブロックチェーンのトレーサビリティ",
    "make-tcard": "返礼感謝カードを作ります",
    "gift-slogan-part-1": "信頼、温度",
    "gift-slogan-part-2": "あなたのために心を込めて用意したギフト",
    "sms-hint-part-1": "ギフト贈り主がお祝いビデオを録画して、送信したら、",
    "sms-hint-part-2":
      "ギフトパスワードを含むモバイルメッセージを受信して​​いるはずです",
    "watch-gcard-from-sender": "ギフト贈り主のお祝いビデオをご覧になります",
    "enter-gift-code-part-1": "モバイルメッセージのギフトパスワード",
    "enter-gift-code-part-2": "を入力してください",
    "gift-code": "モバイルメッセージのギフトパスワード",
    "send-gift-code": "送信",
    "send-tcard-succeed-part-1": "",
    "send-tcard-succeed-part-2": "への返礼感謝カードは送信されました！",
    "tcard-save-fail":
      "返礼感謝カードが保存できません、カスタマーサービスにお問い合わせください",
    "make-tcard-part-1": "",
    "make-tcard-part-2": "への返礼感謝カードを作ります",
    "tcard-instant-preview": "感謝カードをインスタントプレビュー",
    "feedback-name": "返礼者サイン",
    "upload-thank-vid": "返礼者の感謝ビデオの撮影とアップロード",
    "thank-content": "返礼内容",
    "enter-code-error":
      "入力したギフトパスワードが間違っています。確認して修正してください。",
    opening: "オープニングお祝い",
    promoting: "昇進お祝い",
    "new-house": "新居お祝い",
    birthday: "お誕生日お祝い",
    "new-year": "新年お祝い",
    "shooting-now":"今から撮影する。",
    "choose-file":"データを選択する。",
    "vertical-vid-hint":"(画面効果については、「ストレート」ビデオを選択してみてください)"
  },
};

export const LangContext = React.createContext({
  lang: "jp",
  changeLang: () => {},
});
